#!/usr/bin/env bash
set -euo pipefail

# Aranacak kök dizin ve yok sayılacak kalabalık dizinler
SEARCH_ROOT="$HOME"

selected=$(fd . "$SEARCH_ROOT" \
    --exclude "Games" \
    --exclude "VirtualBox VMs" \
    --exclude "go/pkg" \
    --exclude "node_modules" \
    --exclude "target" \
    --exclude "__pycache__" \
    --exclude "venv" \
    --base-directory "$SEARCH_ROOT" | \
    fuzzel --dmenu --prompt="  Files: " --width=85 --lines=15)

[ -z "$selected" ] && exit 0

# Dizin ise terminalde aç, dosya ise xdg-open ile varsayılana gönder
if [ -d "$selected" ]; then
    setsid alacritty --working-directory "$selected"
else
    # xdg-open "$full_path" >/dev/null 2>&1 &
    (setsid xdg-open "$selected") >/dev/null 2>&1  &
fi
